sudo: true
language: haskell
cabal: "3.0"

git:
  depth: 5

cache:
  directories:
  - "$HOME/.cabal/store"
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"

matrix:
  include:
    - ghc: 8.2.2
    - ghc: 8.4.4
    - ghc: 8.6.5


install:
  - gcc   --version
  - ghc   --version
  - cabal --version
  - cabal new-update
  - cabal new-build     --enable-benchmarks --enable-documentation --enable-tests --haddock-all --haddock-hyperlink-source --haddock-internal --only-dependencies

script:
  - cabal new-configure --enable-benchmarks --enable-documentation --enable-tests --haddock-all --haddock-hyperlink-source --haddock-internal
  - cabal new-build     --enable-benchmarks --enable-documentation --enable-tests --haddock-all --haddock-hyperlink-source --haddock-internal
  - cabal new-test

notifications:
  email: false